# Used in text and name
FONT_SIZE=24

AVATAR_SIZE=50

# Margin between avatar and message bubble
AVATAR_MARGIN=5

BUBBLE_X_START= AVATAR_SIZE + AVATAR_MARGIN
BUBBLE_RADIUS=10
BUBBLE_PADDING=BUBBLE_RADIUS

TEXT_X_START= BUBBLE_X_START + BUBBLE_PADDING
